added log filter for request params
original4sure/o4s-logger pull request #14
Opened 2024-02-16 07:04 UTC by rahuljaswani

added log filter for request params

2024-02-16 07:19 UTC, jonscyr requested changes

2024-02-16 07:19 UTC, jonscyr commented on dist/middlewares/koa-logger.middleware.d.ts
> +    const getSuccessLoggerMiddleware: (reqFilter?: any) => (ctx: any, next: any) => Promise<unknown>;
no any please.

2024-02-16 07:19 UTC, jonscyr commented on src/common/common.ts
> +  reqFilter?: any
no any please

2024-02-19 05:34 UTC, rahuljaswani commented on src/common/common.ts
> +  reqFilter?: any
updated the type

2024-02-19 05:34 UTC, rahuljaswani commented on dist/middlewares/koa-logger.middleware.d.ts
> +    const getSuccessLoggerMiddleware: (reqFilter?: any) => (ctx: any, next: any) => Promise<unknown>;
updated the type

2024-02-20 07:48 UTC, jonscyr commented on src/middlewares/koa-logger.middleware.ts
> +  export const getSuccessLoggerMiddleware = (reqFilter?: LogFilter) => {
can you put a description as /** comment doc **/ on what reqFilter does in this function? so that apps using this function knows what it does.

2024-02-20 08:37 UTC, jonscyr approved these changes

2024-02-20 08:37 UTC, merged